appPort: 8080
appName: shipping
externalSecrets:
  enabled: true
resources:
  limits:
    cpu: 2000m
    memory: 3096Mi
  requests:
    cpu: 1600m
    memory: 2500Mi
env:
  - name: JAVA_OPTS
    value: "-Xmx3000m" # Max heap set to 3000m, safely under the 3800Mi limit
#java:
#  xmx: "650m"
