appPort: 8080
appName: shipping
externalSecrets:
  enabled: true
resources:
  limits:
    cpu: 800m
    memory: 3800Mi
  requests:
    cpu: 400m
    memory: 3000Mi
env:
  - name: JAVA_OPTS
    value: "-Xmx3000m" # Max heap set to 3000m, safely under the 3800Mi limit
#java:
#  xmx: "650m"
