appPort: 8080
appName: shipping
externalSecrets:
  enabled: true
resources:
  limits:
    cpu: 2000m
    memory: 4300Mi
  requests:
    cpu: 1600m
    memory: 3800Mi
env:
  - name: JAVA_OPTS
    value: "-Xmx3500m" # Max heap set to 3500m, safely under the 3800Mi limit
#java:
#  xmx: "650m"
